### ISSUE TITLE
Datasets research

### ISSUE THREAD

**Issue by BlaiseCz** [517435708/wapiesz#1]
Search for eng/pln memes datasets with useful metadata

**Comment by SelethenPL** [comment]
Reddit memes dataset (prob r/dankmemes), around 3k, rating included (last update around 3 years ago so could be kinda outdated, but should work for us anyway):
https://www.kaggle.com/sayangoswami/reddit-memes-dataset

**Comment by SelethenPL** [comment]
ImgFlip 575000 (100 meme templates + 500k memes), rating included:
+OCR not needed, memes already with text
+ dataset + scrapper: https://github.com/schesa/ImgFlip575K_Dataset
+ meme generator: https://github.com/schesa/ai-memes
